In [5]:
import pandas as pd
import numpy as no
import matplotlib as plt
import seaborn as sns

In [13]:
vinos = pd.read_csv('vino.csv')

In [19]:
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [23]:
vinos['Wine Type'].unique() # ver los tipos que no se repiten

array(['One', 'Two', 'Three'], dtype=object)

In [25]:
vinos['Wine Type'].value_counts() #~El número de vinos de cata tipo

Wine Type
Two      71
One      59
Three    48
Name: count, dtype: int64

In [29]:
X= vinos.drop('Wine Type', axis=1)

In [33]:
y = vinos['Wine Type']
y #esta es la que vamos a predecir, según sus caracteristicas

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [39]:
from sklearn.model_selection import train_test_split

In [45]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3)

In [57]:
from sklearn.tree import DecisionTreeClassifier
arbol = DecisionTreeClassifier()
arbol.fit(X_train, y_train)

DecisionTreeClassifier()

In [59]:
predicciones = arbol.predict(X_test)

In [61]:
predicciones

array(['Three', 'One', 'Three', 'Two', 'Two', 'Two', 'One', 'Two', 'One',
       'Three', 'Two', 'Two', 'Two', 'One', 'Two', 'One', 'Two', 'Two',
       'Three', 'One', 'One', 'Two', 'Three', 'Three', 'Two', 'One',
       'Three', 'Two', 'One', 'Three', 'Two', 'Three', 'One', 'Three',
       'Three', 'One', 'One', 'One', 'Three', 'One', 'Three', 'Three',
       'Three', 'Two', 'Two', 'Two', 'Two', 'One', 'Three', 'Three',
       'Three', 'Two', 'Three', 'One'], dtype=object)

In [63]:
y_test

138    Three
11       One
151    Three
115      Two
108      Two
129      Two
37       One
38       One
9        One
170    Three
90       Two
128      Two
106      Two
28       One
107      Two
19       One
85       Two
110      Two
158    Three
45       One
40       One
100      Two
165    Three
172    Three
59       Two
30       One
146    Three
60       Two
81       Two
142    Three
126      Two
169    Three
42       One
130    Three
168    Three
23       One
44       One
32       One
144    Three
49       One
143    Three
83       Two
145    Three
120      Two
104      Two
63       Two
88       Two
5        One
132    Three
139    Three
163    Three
78       Two
141    Three
26       One
Name: Wine Type, dtype: object

In [65]:
#Evaluar el modelo

In [67]:
from sklearn.metrics import classification_report, confusion_matrix

In [71]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       0.94      0.94      0.94        16
       Three       0.95      1.00      0.97        18
         Two       0.95      0.90      0.92        20

    accuracy                           0.94        54
   macro avg       0.94      0.95      0.94        54
weighted avg       0.94      0.94      0.94        54



In [75]:
print(confusion_matrix(y_test, predicciones))

[[15  0  1]
 [ 0 18  0]
 [ 1  1 18]]
