### Numpy

In [4]:
import numpy as np
lista= [1,2,3,4]

In [8]:
array= np.array(lista)

In [10]:
array

array([1, 2, 3, 4])

In [14]:
lista2 = [[1,2,3], [4,5,6], [7,8,9]]

In [16]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
array2 = np.array(lista2)

In [26]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy arrays -arange, zeros, ones, linspace, eye

In [37]:
array3= np.arange(5)
array3

array([0, 1, 2, 3, 4])

In [45]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [49]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.ones(3)

array([1., 1., 1.])

In [69]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [77]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

numpy arrays- numeros aleatorios -rand y randn

In [82]:
np.random.rand(5)

array([0.54115635, 0.68101156, 0.59562975, 0.66483038, 0.85676994])

In [84]:
np.random.rand(2,3)

array([[0.80090784, 0.58000516, 0.68203293],
       [0.68949245, 0.84583522, 0.75624439]])

In [92]:
np.random.rand(4)

array([0.63484074, 0.57958911, 0.80669452, 0.33628177])

In [96]:
np.random.randn(4,5)

array([[ 8.20009316e-01,  1.81282648e+00, -1.11924876e+00,
         1.11226357e-01,  1.00816680e+00],
       [-1.01228259e-01,  6.66233871e-01,  5.09285565e-01,
         2.34366798e-01,  2.11307513e+00],
       [-4.39564213e-01, -1.10052574e+00, -9.75987442e-04,
         6.83710631e-01, -1.31498872e+00],
       [-1.12424362e+00,  1.56308760e+00, -1.32963171e-01,
         1.51714035e+00,  5.85948659e-01]])

Numpy arrays -Números aleatorios enteros, randit

In [101]:
np.random.randint(1,20)

18

In [105]:
np.random.randint(1,20)

17

In [109]:
np.random.randint(1,20, 5)

array([11,  8, 19, 17, 11])

In [113]:
arrary = np.random.randint(1, 100, 25) 

In [131]:
arrary

array([97, 78, 80,  2, 52, 22, 50, 59, 77, 26, 39, 12, 92, 57,  3, 73, 81,
       33, 64, 57, 76, 72, 85, 12, 61])

In [133]:
matriz2 = arrary.reshape(5,5)
matriz2

array([[97, 78, 80,  2, 52],
       [22, 50, 59, 77, 26],
       [39, 12, 92, 57,  3],
       [73, 81, 33, 64, 57],
       [76, 72, 85, 12, 61]])

Numpy arrays -max y min

In [140]:
array = np.random.randint(1,100,50)

In [144]:
array

array([15, 75, 27, 68, 87, 14, 29, 40, 27, 85, 99,  2, 97, 88, 16, 81, 41,
       97, 62, 57, 85,  4, 91,  1, 94, 10, 86, 35, 65, 38, 77, 81, 27, 18,
       29, 97, 50, 77, 83, 78, 24, 64, 66, 60, 20, 92, 21, 49, 46, 86])

In [146]:
valor_maximo = array.max()
valor_maximo

99

In [150]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

10

In [156]:
valor_minimo = array.min()
valor_minimo

1

In [162]:
posicion_valor_minimo = array.argmin()
posicion_valor_maximo

10

Arrays indexación una dimension

In [177]:
array4= np.arange(0,10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array4[0]

In [181]:
array[0]

0

In [185]:
array[-9]

1

In [189]:
array[2:4]

array([2, 3])

In [193]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
array[:4]

array([0, 1, 2, 3])

In [201]:
array5 = array.copy()

In [203]:
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy Indexación en arrays de 2 o más dimensiones

In [208]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [212]:
array[0]

array([1, 2, 3])

In [216]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [220]:
array[0][0]

1

In [224]:
array[0,0]

1

In [228]:
array[1,1]

5

In [232]:
array[:,0]

array([1, 4, 7])

In [240]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Seleccionar elementos de un array según una condición

array = np.arange(1,14)

In [247]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [251]:
condicion = array > 5

In [255]:
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True])

In [259]:
array[condicion]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [263]:
array6= array[condicion]

In [265]:
array6

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [269]:
array[array> 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

Operaciones sobre los arrays

In [275]:
array7 = np.arange(0,10)
array7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [279]:
array7 + array7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [283]:
array7 - array7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [285]:
array7 * array7

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [291]:
array7 +40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [293]:
array7 -3

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [297]:
array8 = np.arange(5,15)

In [299]:
array8

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [301]:
array8 - array7

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [305]:
array8 * array7

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [307]:
np.sqrt(array8)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [309]:
np.max(array7)

9

#Ejercicios

In [324]:
arrayE = np.arange(10,40)

In [326]:
arrayE

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [328]:
arrayE = arrayE.reshape(3,10)
#con reshape trasformamos el array de una dimensión a tres

In [330]:
arrayE

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [334]:
arrayE[0][9]

19

Crea un array de una dimensión con 9 valores enteros aleatorios entre 0 y 100 
Convierte ese array enuna matriz de 2 dimensiones(3 filas y 3 columnas)
muestra por pantalla el valor del elemento de la matriz, de la esquina inferior derecha

In [357]:
ejer2 = np.random.randint(0,100,9)
ejer2

array([89, 82, 70, 40, 53, 34, 31, 57, 64])

In [361]:
matriz = ejer2.reshape(3,3)

In [363]:
matriz

array([[89, 82, 70],
       [40, 53, 34],
       [31, 57, 64]])

In [369]:
matriz[2][2]

64